"""Add updated_at to comments

Revision ID: cb33998e1ad1
Revises: 0c2b8a0efad2
Create Date: 2025-07-08 10:52:23.999814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb33998e1ad1'
down_revision = '0c2b8a0efad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_reply', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key('fk_comments_parent_id', 'comments', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_parent_id', type_='foreignkey')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_approved')
        batch_op.drop_column('is_reply')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
